#!/bin/sh
#
# Copyright 2015-2017 The REST Switch Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, Licensor provides the Work (and each Contributor provides its
# Contributions) on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including,
# without limitation, any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A PARTICULAR
# PURPOSE. You are solely responsible for determining the appropriateness of using or redistributing the Work and assume any
# risks associated with Your exercise of permissions under this License.
#
# Author: John Clark (johnc@restswitch.com)
#

if [ ! -s /etc/config/aws-iot ]; then
	touch /etc/config/aws-iot

	thing_name=$(dd if=/dev/mtd2ro bs=1 count=9 skip=1024 2>/dev/null)

	uci -q batch <<-EOF
		delete aws-iot.$thing_name
		set aws-iot.$thing_name='thing'
		set aws-iot.$thing_name.host=''
		set aws-iot.$thing_name.port='8883'
		set aws-iot.$thing_name.ca='/etc/aws-iot-certs/root_ca.pem'
		set aws-iot.$thing_name.cert='/etc/aws-iot-certs/cert.pem'
		set aws-iot.$thing_name.key='/etc/aws-iot-certs/private.pem'
	EOF

	uci commit aws-iot
fi

exit 0
